### ISSUE TITLE
cannot build on microos

### ISSUE THREAD

**Issue by skatcat743** [axtloss/tetrio_flatpak#2]
I do not know if this is a openSuse MicroOS problem or a skill issue. 
Dependencies were successfully installed.
Do you know if it is feasible to build on a more traditional Linux system then transfer the built package over? How often is upstream updated?
```
flatpak run org.flatpak.Builder --user build-dir io.tetr.tetr.io.yml
Downloading sources
Downloading https://tetr.io/about/desktop/builds/TETR.IO%20Setup.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.8M  100 67.8M    0     0  22.8M      0  0:00:02  0:00:02 --:--:-- 22.8M
Initializing build dir
Committing stage init to cache
Starting build of io.tetr.tetr.io
Portal call failed: Failed to start command: Failed to execute child process “fusermount” (No such file or directory)
========================================================================
Building module tetrio in /home/skatcat743/Downloads/tetrio_flatpak-main/.flatpak-builder/build/tetrio-1
========================================================================
Running: install -Dm755 tetrio-run /app/bin/tetrio-run
error: Build directory /home/skatcat743/Downloads/tetrio_flatpak-main/.flatpak-builder/rofiles/rofiles-FyRZVo not initialized, use flatpak build-init
Error: module tetrio: Child process exited with code 1
```

**Comment by axtloss** [comment]
The log has this error message:
> Portal call failed: Failed to start command: Failed to execute child process “fusermount” (No such file or directory)

I'm not fully sure which package provides the `fusermount` command, but you probably have to install this.

If all doesn't work, try installing flatpak-builder with your host package manager instead of using the flatpak one

**Comment by skatcat743** [comment]
yep you would think dependency would be part of the org.flatpak.Builder or the freedesktop one.
